### ISSUE TITLE
Add callback for rigidbody's _integrate_forces

### ISSUE THREAD

**Issue by chunribu** [derkork/godot-statecharts#104]
Thank you for making this great plugin! It would be helpful if there was support for rigid body characters.

**Comment by derkork** [comment]
I'm not sure that this can be done. The problem is that `_integrate_forces` is a specific callback per `RigidBody` as opposed to the other callbacks like `_physics_process` or `_process` which are more stage-like callbacks for all nodes. This means that the Godot engine will call this only on `RigidBody` nodes, and will also ensure that the physics representation of the `RigidBody` is in a proper state before this callback is being called (see https://github.com/godotengine/godot/blob/578d937927ea9735aa7a8e0535f57801406b0b82/scene/2d/physics/rigid_body_2d.cpp#L172). 

So to intercept this callback the state chart's nodes would need to be `RigidBody` so we get this callback. And even then it would not be very useful because if the state chart's node would now emit a signal that other `RigidBody` nodes use to run their `_integrate_forces` step, then these other `RigidBody` nodes have not yet been prepared by the engine to run this step. 

So I think there is no way around manually checking the for the currently active state(s) inside of `_integrate_forces`. For this you would need to get hold of the state chart node that represents the state you are interested in (e.g. `%Running`)  and then check if it is active (e.g. `if %Running.active`) and then run the appropriate code.

**Comment by chunribu** [comment]
@derkork Thank you so much for your explanation and suggestions, I will try it
