### ISSUE TITLE
HistoryState doesn't work

### ISSUE THREAD

**Issue by lavstudia** [derkork/godot-statecharts#11]
Please check HistoryState does not work, I added it as a child node to CompoundState, but when HistoryState transitions to history <null> and _state_restore is not called

**Comment by derkork** [comment]
I cannot reproduce this, it seems to work fine in the history state demo. Could you give some more information about how you set this up or create a small example project that shows the problem?

**Comment by lavstudia** [comment]
Yes, sure. Here is a simple example illustrating the described problem
[test_fsm_history.zip](https://github.com/derkork/godot-statecharts/files/11373534/test_fsm_history.zip)

**Comment by derkork** [comment]
Ok the problem seems to be that I didn't describe the usage of the history state very well. If you want to return to what the history state has saved you need to transition to the history state itself, not to the parent compound state, e.g. in your example:

![image](https://user-images.githubusercontent.com/327257/235748944-e559652a-d465-4437-90ac-f4c0b16af140.png)

If you transition to the parent state it will just be a normal transition and no history will be restored. 


https://user-images.githubusercontent.com/327257/235749588-3ae5bb07-164c-4146-9193-2a6f6d5359a9.mp4

I will update the documentation to give better instructions on how to use it.
