### ISSUE TITLE
expression_guard.is_satisfied(): Cannot get path of node as it is not in a scene tree.

### ISSUE THREAD

**Issue by Jan-PieterInghels** [derkork/godot-statecharts#129]
I'm encountering an issue where an error is thrown when an expression property is set on nodes which are freed.

This occurs in the following scenario:

I connect the following signal: area2D.body_exited()

```
func _on_area2D_body_exited(body):
	if body.is_in_group("player"):
		state_chart.set_expression_property('player_in_range', false)
```

The issue occurs when the expression property is attempted to be set on freed objects.

This happens when the node is freed and the signal is triggered as a result.
The node can be freed by itself, or it can be freed by changing scenes. In both cases, when the signal is triggered, the following error message appears: 

> E 0:00:29:0310   expression_guard.gd:18 @ is_satisfied(): Cannot get path of node as it is not in a scene tree.
  <C++ Error>    Condition "!is_inside_tree()" is true. Returning: NodePath()
  <C++ Source>   scene\main\node.cpp:2084 @ Node::get_path()
  <Stack Trace>  expression_guard.gd:18 @ is_satisfied()
                 transition.gd:74 @ evaluate_guard()
                 state_chart_state.gd:271 @ _process_transitions()
                 compound_state.gd:134 @ _process_transitions()
                 compound_state.gd:126 @ _process_transitions()
                 state_chart.gd:148 @ _run_changes()
                 state_chart.gd:127 @ set_expression_property()
                 monster_03.gd:151 @ _on_player_detector_body_exited()
                 scene_manager.gd:31 @ _load_menu_scene()

Is this by design and should I work around this myself, or should this case be handled by the library itself?

Amazing tool by the way, it simplifies a lot of what I'm trying to do. Should come native with Godot imho!

**Comment by Jan-PieterInghels** [comment]
I agree with your reasoning, I'd prefer getting an explicit error thrown over implicit error handling behind the scenes, as long as there are valid use cases where the error communicates a mistake of the programmer. I haven't encountered those myself, but I assume the error is there for good reason.

That being said, in this example it's not a mistake and the functionality I'm implementing is being executed as I'd expect it to, meaning the error message is thrown, but it works. Therefore an error message feels a bit harsh to me. Maybe a warning is more appropriate? One example of this that I know of in native Godot is for Tweens. When you try to remove a tween in certain conditions, the following warning message might get thrown:
`Target object freed before starting, aborting Tweener.`

Since I believe this is not a super niche use case, another suggestion could be to add an exported variable to every type of state which would be false by default, but if toggled true, 'error swallowing magic' happens. This way, error handling only happens implicitly. Maybe something like `free_state_if_active` or `disable_node_path_error`. The error / warning could then refer to it as well to clearly communicate the right course of action to get rid of it.
What do you think?

**Comment by derkork** [comment]
Hi, sorry for the slow response, I am currently away from the computer for a few days and only have limited access to the internet. I would like to avoid configuration flags if I can do without them because they increase the complexity of the level of the library. I`ll try to come up with a way that “just works“.

**Comment by Jan-PieterInghels** [comment]
I ended up avoiding this problem by sending events instead of relying on expression properties, like this:
```
func _on_area2D_body_exited(body):
	if body.is_in_group("player"):
		state_chart.send_event("player_in_range")
```

```
func _on_player_detector_body_exited(body):
	if body.is_in_group("player"):
		state_chart.send_event("player_out_of_range")
```

So maybe, the solution lies in changing the way expression properties are handled internally?
Instead of setting properties directly, an event could be fired. A method can be bound to this event which sets the expression property to the desired value. This avoids an expression property change from executing when being freed, while keeping the existing functionality. Just an idea of course!

**Comment by derkork** [comment]
I'm back at a computer and had a look into the code and in line 18 it actually runs the expression itself. At this point in time no part of the state chart could be freed already unless you hard `free` the state chart or its parent node before setting the expression property. I cannot see such a thing happen in your example code. So from that I would deduce that the expression itself accesses something that is no longer valid. Could you post the expression you are using and maybe add some description of the variables it is using (if any)?

**Comment by Jan-PieterInghels** [comment]
The project I'm working on has a lot of moving parts. I tried to create an MVP in a new project but so far without success, so the best I can do at the moment is provide you with a video of the setup.

https://github.com/user-attachments/assets/8e0e6c15-7692-4940-a1cb-6612813b2d08

**Comment by derkork** [comment]
Thanks a lot for providing the video, it helped clearing up why this happens:


1. You call `change_scene_to_packed` which will remove the root node of the current scene from the tree but not dispose it yet (see https://github.com/godotengine/godot/blob/f135f729b91e61e6844159a535a7474335ec8d52/scene/main/scene_tree.cpp#L1429).
2. Side effects play out, and your monster`s `_on_player_detector_body_exited` is called. 
3. The monster sets an expression property on the state chart.
4. The call fails because the state chart is no longer in the tree (because of 1) but not destroyed.

In this particular case, the node doesn't strictly need to be in the tree to execute the functionality, we actually only need the path to be part of the error message for debugging (it's nice to know which node caused a problem).  So I could add code that works around this (at the expense that the library cannot give you the location of the node in an error message if the node is not in the tree). This would silence the problem in your particular case but still not withhold important error messages from the developer.

That being said, I'm not sure if you really want to run code this way. In this particular case it may not make much of a difference if enemy code still executes and does things when you are switching away from the scene but in general having a setup like this may lead to _interesting_ effects down the road. So you may want to implement a somewhat more controlled shutdown loop to prevent this from happening.

**Comment by Jan-PieterInghels** [comment]
Thank you for the review! I'll refine the scene switching code. Unexpected behaviour is certainly not what I'm aiming for here.

**Comment by Jan-PieterInghels** [comment]
> 1. You call `change_scene_to_packed` which will remove the root node of the current scene from the tree but not dispose it yet (see https://github.com/godotengine/godot/blob/f135f729b91e61e6844159a535a7474335ec8d52/scene/main/scene_tree.cpp#L1429).
>
> 2. Side effects play out, and your monster's `_on_player_detector_body_exited` is called.
> 
> 3. The monster sets an expression property on the state chart.
> 
> 4. The call fails because the state chart is no longer in the tree (because of 1) but not destroyed.
>
> So you may want to implement a somewhat more controlled shutdown loop to prevent this from happening.


After reviewing the code, I'm not sure what you are suggesting with 'a somewhat more controlled shutdown loop'?
Looking at [the docs](https://docs.godotengine.org/en/stable/tutorials/scripting/change_scenes_manually.html), the first suggested method of performing a scene change is to call `change_scene_to_file()` or `change_scene_to_packed`.

I tried both, including pausing the scene tree until the `change_scene_to_...` returns OK. This does not work however, since signals are still emitted under a paused scene tree, so the error still occurs.

> That being said, I'm not sure if you really want to run code this way. In this particular case it may not make much of a difference if enemy code still executes and does things when you are switching away from the scene but in general having a setup like this may lead to interesting effects down the road..

The [docs](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-change-scene-to-packed) point out that while the current scene is immediately removed from the tree, at the end of the frame it will be freed and the new one gets instantiated. Since everything happens in the time span of 1 frame, I have a hard time seeing how this might lead to _interesting_ behaviour?

So far, the only issue I have run into is this state chart library error, but I'm happy to learn if that's due to my lack of experience with Godot! Any help in this area is very much appreciated.

**Comment by derkork** [comment]
Well personally I'm not a huge fan of `change_scene_to_file/packed` because these calls assume a lot about how the game is made up and really only work for the simplest of setups. The minute you want something like a loading screen or even just a simple fade transition these don't work anymore. There are nice for getting something done quickly but thats about it. As for "controlled shutdown" i meant something like a script which makes sure that all game components are freed in a proper way that doesn't have unwanted side effects. For example there may be code in enemies to increase a point counter when the enemy is freed. However if this code also runs when you switch a level then this may mess with your highscore system. Similarly in your case, you get a `body_exited` event which just happens because Godot deletes the body and not because its part of your intended gameplay. And there are basically two ways in which you can approach this.

1. Say "i don't care, it will work out just fine" in which case you can also ignore any warnings you might get and move on. And this is a perfectly valid strategy.
2. Make sure things are shut down in a controlled way that doesn't introduce unwanted side effects. E.g. broadcast a "hey, the game is going to be unloaded" message which game elements can use to unsubscribe from anything they are subscribed to and shut themselves down in a controlled fashion. This may be of course overkill and I freely admit that I'm a bit of a control freak with this because I do business software in may day job where I want as little undefined behaviour as possible. 

In any case, I'll go over every usage of `get_path` in the library and check if this can be made a bit more robust, so at least you don't get a hard error for what is basically a debug output.
