### ISSUE TITLE
Save/Load State

### ISSUE THREAD

**Issue by TornadoStorm** [derkork/godot-statecharts#144]
Is it in any way possible to store and restore the current state of the state chart itself? I would like to use this addon with rollback netcode, which requires this functionality so that the chart can be "rewinded" to previous frames at any point if needed.

**Comment by derkork** [comment]
This feature is currently only partially implemented (for the history states) but that code could probably be adapted to store the whole state chart's current state when called at the right time.  However implementing this at the state  chart is only half of the story because usually you would also have scripts attached to the signals of the state chart and these scripts also have state which may not be as easy to roll back.

**Comment by TornadoStorm** [comment]
Thanks for the response & insight!

That should be fine. I'm using the [Delta Rollback](https://gitlab.com/BimDav/delta-rollback/) addon and there, anything that needs to have a state loaded and saved just needs to implement a _save_state() and _load_state() function, so attached scripts would also rollback on their own.

I am thinking of implementing a new node for the state chart similar to the history node, but has 3 fields; deep, save event and load event. When the save event is triggered, it collects and stores the state of the parent node (excluding anything from the current node), and then restores the parent node when load state is triggered, calling an exception if nothing was saved. Thoughts on this?

**Comment by derkork** [comment]
I'm not sure if this necessarily needs to be a child of the state chart but in general the approach should be workable. These things tend to have a ton of edge cases though so there will likely be some hiccup along the way. But only one way to find out 😁
