### ISSUE TITLE
Throw exception if SendEvent() is called with invalid event name

### ISSUE THREAD

**Issue by mccrae-ben** [derkork/godot-statecharts#150]
*Note* I'm not a super strong programmer so take everything with a grain of salt 😄 

Have been using this in a C# project and noticed the following:
- I have a Transition node with an event name like "ToShooting"
- In my class where I want to send the event, I have _stateChart.SendEvent("ToShoot")
- This does not produce an error despite "ToShooting" not matching "ToShoot". 

*My Implemented Solution Which Is Probably Not Very Good*
- Added a "get_event" function to the transition.gd script that returns the event
- Added a wrapper function GetEvent to Transition.cs
- Added a function to StateChart.cs that loops through ever child node of the StateChart and look for scripts that end in "transition.gd" and adds them to a list `MyTransitionEventNames`
- In the SendEvent wrapper, I added `if(!MyTransitionEventNames.Contains(eventName)) throw new ArgumentException("No event with this name exists in this StateChart");`

The debugger definitely mitigates this issue a lot but just thought I'd share. Excellent plugin and the C# wrappers are much appreciated!

**Comment by derkork** [comment]
First off, thanks a lot for suggesting this, it's really feedback like this, that helps making this library useful to everyone. I agree that it would indeed be helpful if the developer is notified when trying to do something that is most likely not going to work. 

I do however think that throwing an exception is a bit excessive here, because there are cases when sending unknown events is actually desired (e.g. when doing some kind of event bus and forwarding all events to the state chart). If we know throw exceptions, we break these use cases and that would make other people unhappy. Another thing is that GDScript actually has no concept of exceptions and I would very much like the library to behave the same way in GDScript and C#. 

So what can be done is adding a warning that is printed to the console. This will clearly indicate to the developer that something is wrong and will work equally in C# and GDScript. To not annoy developers who send unknown events to the state chart on purpose, this warning can also now  be turned off per state chart:

![image](https://github.com/user-attachments/assets/c2f78a97-80d9-4dec-8938-a9202ce4e426)

The warning will also only be enabled in debug builds to avoid iterating the event names on every event sent.  This is now in 0.17.1 and will go into the asset library soon. If you want to [update](https://derkork.github.io/godot-statecharts/installation#updating-from-an-earlier-version),  you can grab the [new version](https://github.com/derkork/godot-statecharts/releases/tag/v0.17.1) from Github.

**Comment by mccrae-ben** [comment]
makes sense, thanks!
