### ISSUE TITLE
strange_warning_keeps_showing_up: core/variant/variant_utility.cpp:1100 - State chart has no root state. Ignoring call to `send_event`

### ISSUE THREAD

**Issue by geeemok** [derkork/godot-statecharts#151]
first of all, thanks to this project. its quite amazing.
everything works well(at least the beheavior is correct). but the console keep showing  a warning.
i dont know what cause it. but its actually send the event ,and the state changed correctly

`core/variant/variant_utility.cpp:1100 - State chart has no root state. Ignoring call to `send_event``

**Comment by derkork** [comment]
Could it be that you have maybe a second empty instance of a state chart with no root state running somewhere in a scene?

**Comment by geeemok** [comment]
[debug_test.zip](https://github.com/user-attachments/files/17609480/debug_test.zip)
here is the minimal test for that situation.  
once u opend this file, the console will report that error:
```
core/variant/variant_utility.cpp:1100 - State chart has no root state. Ignoring call to `send_event`
```

**Comment by geeemok** [comment]
it's a quite simple scence.
the root will keep send a event on process
```
func _process(_delta: float) -> void:
	if toggle:	$StateChart.send_event(&"to_b")
```

**Comment by derkork** [comment]
Thanks for sharing a reproducer. The problem is that your main scene is a `@tool` script.

```gdscript
@tool
extends Node2D

@export var toggle := true

func _process(_delta: float) -> void:
	if toggle:	$StateChart.send_event(&"to_b")
```

This will try to send events to the state chart in the editor, but because the state chart is not designed to be run in the editor it will not be initialized and therefore give you the error message you saw. You can fix this in two ways - either don't make your script a `@tool` script or - if you need this for some in-editor validation, add a blocker to the `_process` function such that it doesn't run in the editor:

```gdscript
@tool
extends Node2D

@export var toggle := true

func _process(_delta: float) -> void:
       # don't run in the editor
	if Engine.is_editor_hint():
		return
		
	if toggle:	$StateChart.send_event(&"to_b")

```

**Comment by geeemok** [comment]
got it,thanks!
