### ISSUE TITLE
AntHill demo calling "initialized" too early

### ISSUE THREAD

**Issue by BencePaul** [derkork/godot-statecharts#31]
Hi, 

Thanks for the great addon to Godot. I am a newbie to Godot so please excuse any mistakes below. I was trying to understand the AddOn better by running the AntHill demo in Godot v4.1.1(stable) and the ants never switched from "Initializing" to "Seeking food" state. I used the debugger (nice tool) to see that the signal was never acted on. So I added a timer to the Ant scene, with a wait time of 3 seconds. When it timed out, I sent the signal again (via `timer.timeout.connect(func (): state_chart.send_event("initialized"))`, and it successfully started the demo.

I'm sure there's a more elegant way of doing this, but it seems that the signal is sent too early?

**Comment by derkork** [comment]
Yes this is a side effect of the fix for https://github.com/derkork/godot-statecharts/issues/28 . The initial state of the state chart is only entered with one frame delay, so that nodes higher up in the tree have a chance to run their ready functions before the state chart calls any state logic. Sadly this broke the ant demo because it runs a state transition in _ready.  it is easily fixed though by running the state transition one frame delayed as well, e.g. like this:

![image](https://github.com/derkork/godot-statecharts/assets/327257/960b6cf2-d4fc-452a-bb47-a0ef333b64ff)

I'll push a fix for this and add some info in the manual about it.
