### ISSUE TITLE
StateChart goes into infinite loop

### ISSUE THREAD

**Issue by Shadowblitz16** [derkork/godot-statecharts#34]
[humans.zip](https://github.com/derkork/godot-statecharts/files/12615404/humans.zip)
your state.gd is going into a infinite loop

**Comment by derkork** [comment]
You've set up "Horizontal"/"Idle" to immediately jump to "Horizontal"/"Dash", and you have set up "Horizontal"/"Dash" to immediately go to "Horizontal"/"Idle" both with a guard that the "Grounded" state is active. 

![image](https://github.com/derkork/godot-statecharts/assets/327257/e50c98e1-893e-43f1-8af4-a08f167e5d34)

This forms an infinite loop. You will probably want to add an event for these transitions to trigger otherwise they will infinitely ping-pong back and forth.
