### ISSUE TITLE
support for _integrate_forces?

### ISSUE THREAD

**Issue by tupcakes** [derkork/godot-statecharts#6]
From what I've been able to tell this state chart implementation doesn't appear to work with _integrate_forces? If I'm understanding that correctly, is that something that could be added to the State class?

_integrate_forces is used primarily when controlling StaticBody2D objects in kinematic mode.

**Comment by derkork** [comment]
Hi @tupcakes , could you elaborate on your use case for this? 

Right now the approach of using signals this library uses does not lend itself very well to `_integrate_forces` because `_integrate_forces` is a member method of `RigidBody2D`/`RigidBody3D` and as such the state machine has no way of simulating this call because it is called at the right time by the `RigidBody2D`/`RigidBody3D` itself. 

What could work is some kind of dispatching mechanism that reads current state machine state and then dispatches to a certain method but that's a lot less elegant as it's basically a glorified switch/case and it would require you to either refer to states in your code (which I think miss the point of using this library) or repeat your state structure somehow in a secondary node structure which isn't great from a maintenance point of view.  Both options are not very appealing. 

But in any case, if you could tell me a bit more about your use case, maybe a better way comes to mind, so I'd very much appreciate if you could give me some details. Thanks a lot!

**Comment by derkork** [comment]
Thanks for the explanation. I cannot see however where the state charts come into play here. Does the ship have any states that would affect how it moves physically? Do states limit what input is available?

**Comment by derkork** [comment]
I'm closing this as I would need more information to derive any meaningful action from it and it's been inactive for two weeks. Please reopen it if you want to continue the discussion.
