### ISSUE TITLE
`CompoundState` reports error upon only having 1 child state

### ISSUE THREAD

**Issue by mieldepoche** [derkork/godot-statecharts#96]
![image](https://github.com/derkork/godot-statecharts/assets/71937306/13d55a21-015c-4e9c-ba69-4beb1f214c94)
- there's a typo
- the minimum should be one child, not two. The [docs](https://github.com/derkork/godot-statecharts/blob/main/manual/manual.md#compound-states) say so too.

**Comment by derkork** [comment]
There is an obvious typo here which I will fix. Technically it will work with 1 child state but I don't see a use case where I would use a compound state with a single child state rather than just the child state itself. So maybe I'd change the error message with a single child to something like "compound state only has a single child, consider removing the compound state and use the child state directly". What do you think?
